---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-soapui-debian-min
    image: debian:9

provisioner:
  name: ansible
  playbooks:
    converge: ../soapui-min/converge.yml

scenario:
  name: debian-min-soapui-min

verifier:
  name: testinfra
  directory: ../soapui-min/tests
