---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-soapui-debian-min
    image: debian:9
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../soapui-min/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: debian-min-soapui-min

verifier:
  name: testinfra
  directory: ../soapui-min/tests
  lint:
    name: flake8
