---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-soapui-ubuntu-min
    image: ubuntu:18.04
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: ubuntu-min-soapui-min

verifier:
  name: testinfra
  directory: ../soapui-min/tests
  lint:
    name: flake8
