---
language: python
python: '3.8.2'

env:
  global:
    - MOLECULEW_USE_SYSTEM=true

jobs:
  include:
    - env:
        - MOLECULE_SCENARIO=default
        - MOLECULEW_ANSIBLE=2.9.1
    - env:
        - MOLECULE_SCENARIO=ubuntu-min-soapui-min
        - MOLECULEW_ANSIBLE=2.7.15
    - env:
        - MOLECULE_SCENARIO=ubuntu-min-soapui-max
        - MOLECULEW_ANSIBLE=2.7.15
    - env:
        - MOLECULE_SCENARIO=ubuntu-max-soapui-min
        - MOLECULEW_ANSIBLE=2.9.1
    - env:
        - MOLECULE_SCENARIO=ubuntu-max-soapui-max
        - MOLECULEW_ANSIBLE=2.9.1

# Require Ubuntu 18.04
dist: bionic

# Require Docker
services:
  - docker

install:
  # Install dependencies
  - ./moleculew wrapper-install

  # Display versions
  - ./moleculew wrapper-versions

script:
  - ./moleculew test --scenario-name=$MOLECULE_SCENARIO

cache:
  directories:
    - $HOME/.moleculew

branches:
  only:
    - master
    - develop
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
