#!/usr/bin/env bash
set -e

for d in molecule/*/ ; do
    d=$(echo ${d#molecule/})
    scenario=$(echo $d | sed 's:/*$::')
    if [[ "$scenario" == 'soapui-max' ]] || [[ "$scenario" == 'soapui-min' ]] ; then
        continue
    fi
    echo "** Running Scenario '$scenario' **"
    ./moleculew test --scenario-name=$scenario
done