---
- name: load version vars
  with_first_found:
    - '../vars/versions/{{ soapui_version }}.yml'
    - ../vars/versions/main.yml
  include_vars: '{{ item }}'

- name: assert version vars
  ansible.builtin.assert:
    that:
      - "soapui_redis_sha256sum not in (None, '')"

- name: create download directory
  ansible.builtin.file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ soapui_download_dir }}'

- name: download SoapUI
  ansible.builtin.get_url:
    url: '{{ soapui_download_url }}/{{ soapui_redis_filename }}'
    dest: '{{ soapui_download_dir }}/{{ soapui_redis_filename }}'
    checksum: 'sha256:{{ soapui_redis_sha256sum }}'
    force: no
    mode: 'u=rw,go=r'

- name: create SoapUI installation directory
  become: yes
  ansible.builtin.file:
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
    dest: '{{ soapui_install_dir }}'

- name: install unarchive dependencies (zypper)
  become: yes
  ansible.builtin.zypper:
    name:
      - gzip
      - tar
    state: present
  when: ansible_pkg_mgr == 'zypper'

- name: install SoapUI
  become: yes
  ansible.builtin.unarchive:
    src: '{{ soapui_download_dir }}/{{ soapui_redis_filename }}'
    remote_src: yes
    extra_opts: '--strip-components=1'
    dest: '{{ soapui_install_dir }}'
    owner: root
    group: root
    creates: '{{ soapui_install_dir }}/bin'

- name: fix for SoapUi 5.6.0 Check that the xmlbeans-xpath-2.6.0.jar exists
  ansible.builtin.stat:
    path: "{{ soapui_install_dir }}/lib/xmlbeans-xpath-2.6.0.jar"
  register: xmlbeans_xpath_260_result
  when:
    - soapui_version in ('5.6.0')

- name: fix for SoapUi 5.6.0
  become: yes
  ansible.builtin.command: " mv {{ item }} {{ item }}.old  "
  with_items:
    - "{{ soapui_install_dir }}/lib/xmlbeans-xpath-2.6.0.jar"
    - "{{ soapui_install_dir }}/lib/xmlbeans-xmlpublic-2.6.0.jar"
  when:
    - soapui_version in ('5.6.0')
    - xmlbeans_xpath_260_result.stat.exists

# Set SoapUI facts
- name: create Ansible facts.d directory
  become: yes
  ansible.builtin.file:
    state: directory
    dest: /etc/ansible/facts.d
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: install SoapUI SDK facts
  become: yes
  ansible.builtin.template:
    src: facts.j2
    dest: /etc/ansible/facts.d/soapui.fact
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: re-read facts
  ansible.builtin.setup:
    filter: ansible_local

- name: install SoapUI link
  become: yes
  ansible.builtin.file:
    state: link
    src: '{{ soapui_install_dir }}/bin/soapui.sh'
    dest: '/usr/local/bin/soapui.sh'

- name: install SoapUI desktop file
  become: yes
  ansible.builtin.template:
    src: SoapUI.desktop.j2
    dest: '/usr/share/applications/SoapUI.desktop'
    owner: root
    group: root
    mode: 'u=rw,go=r'

- name: 'find all sh files in {{ soapui_install_dir }}'
  ansible.builtin.find:
    paths: '{{ soapui_install_dir }}/bin'
    patterns: '*.sh'
  register: soapui_sh_files
  when: not soapui_java_home in (None, '', omit)

- name: extend path with java bin folder in soapui sh files
  become: yes
  ansible.builtin.lineinfile:
    dest: '{{ item.path }}'
    insertafter: '#!/bin/sh'
    line: 'PATH={{ soapui_java_home }}/bin:$PATH'
  loop: '{{ soapui_sh_files.files }}'
  when: not soapui_java_home in (None, '', omit)
