---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-soapui-fedora
    image: fedora:37

provisioner:
  name: ansible
  playbooks:
    converge: ../soapui-min/converge.yml

scenario:
  name: fedora-soapui-min

verifier:
  name: testinfra
  directory: ../soapui-min/tests
