---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-soapui-ubuntu-min
    image: ubuntu:20.04
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../soapui-min/playbook.yml
  lint: |
    set -e
    yamllint .
    ansible-lint
    flake8

scenario:
  name: ubuntu-max-soapui-min

verifier:
  name: testinfra
  directory: ../soapui-min/tests
  lint:
    name: flake8
