---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-soapui
      soapui_version: '4.6.4'

  post_tasks:
    - name: verify soapui facts
      assert:
        that:
          - ansible_local.soapui.general.version == '4.6.4'
          - ansible_local.soapui.general.home == '/opt/soapui/4.6.4'
