---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-soapui-opensuse
    image: opensuse/leap:15.4

provisioner:
  name: ansible
  playbooks:
    converge: ../soapui-min/converge.yml

scenario:
  name: opensuse-soapui-min

verifier:
  name: testinfra
  directory: ../soapui-min/tests
