---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-soapui-centos-min
    image: centos:7
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../soapui-min/playbook.yml

scenario:
  name: centos-min-soapui-min

verifier:
  name: testinfra
  directory: ../soapui-min/tests
  lint:
    name: flake8
