---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-soapui-ubuntu-min
    image: ubuntu:22.04

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  options:
    v: true

scenario:
  name: ubuntu-max-soapui-max-java-home

verifier:
  name: testinfra
  directory: tests
