---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-soapui-ubuntu-max
    image: ubuntu:20.04

provisioner:
  name: ansible
  playbooks:
    converge: ../soapui-max/playbook.yml

scenario:
  name: default

verifier:
  name: testinfra
  directory: ../soapui-max/tests
  lint:
    name: flake8
