---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-soapui-ubuntu-1804
    image: ubuntu:18.04

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  directory: ../soapui-max/tests
  lint:
    name: flake8
