---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-soapui-ubuntu-max
    image: ubuntu:20.04
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../soapui-max/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: ubuntu-max-soapui-max

verifier:
  name: testinfra
  directory: ../soapui-max/tests
  lint:
    name: flake8
