---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-soapui-centos-max
    image: redhat/ubi8
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../soapui-max/playbook.yml

scenario:
  name: ubi-max-soapui-max

verifier:
  name: testinfra
  directory: ../soapui-max/tests
  lint:
    name: flake8
