---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-soapui-ubuntu-min
    image: ubuntu:18.04

provisioner:
  name: ansible
  playbooks:
    converge: ../soapui-max/converge.yml

scenario:
  name: ubuntu-min-soapui-max

verifier:
  name: testinfra
  directory: ../soapui-max/tests
