---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-soapui
      soapui_version: '5.5.0'

  post_tasks:
    - name: verify soapui facts
      assert:
        that:
          - ansible_local.soapui.general.version == '5.5.0'
          - ansible_local.soapui.general.home == '/opt/soapui/5.5.0'
